name: sae_lens
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # PyTorch (GPU version)
  # Uses 12.4 toolkit (compatible with 12.6 drivers)
  - pytorch
  - pytorch-cuda=12.4

  # Standard Libraries (Conda-Forge)
  - transformers>=4.38.1
  - plotly>=5.19.0
  - datasets>=3.1.0
  - nltk>=3.8.1
  - safetensors>=0.4.2,<1.0.0
  - python-dotenv>=1.0.1
  - pyyaml>=6.0.1
  - typing-extensions>=4.10.0
  - tenacity>=9.0.0
  - boto3>=1.34.101
  - botocore>=1.34.101
  - beautifulsoup4>=4.12.0
  - tabulate>=0.9.0
  - trio>=0.30.0

  # Dev Tools
  - pytest>=8.0.2
  - pytest-cov>=4.1.0
  - pre-commit>=3.6.2
  - pyright=1.1.365
  - ruff>=0.7.4
  - mkdocs>=1.6.1
  - mkdocs-material>=9.5.34

  # Pip Section
  - pip
  - pip:
    # Packages not in Conda or requiring specific versions
    - kaleido>=1.2.0
    - transformer-lens>=2.16.1
    - babe>=0.0.7
    - plotly-express>=0.4.1
    - simple-parsing>=0.1.6
    - mamba-lens>=0.0.4
    - ansible-lint>=24.2.3 ; platform_system != "Windows"
    - docstr-coverage>=2.3.2
    - mkdocs-autorefs>=1.4.2
    - mkdocs-redirects>=1.2.1
    - mkdocs-section-index>=0.3.9
    - mkdocstrings>=0.25.2
    - mkdocstrings-python>=1.10.9
    - eai-sparsify>=1.1.1
    - mike>=2.0.0
    - dictionary-learning>=0.1.0

# conda env create -f conda_env.yml -p /scratch/Collin/envs/sae